- name: Install and run nginx
  hosts: web
  become: yes 
  tasks:
  - name: Install nginx
    ansible.builtin.package:
      state: present
      name: nginx
  - name: start the nginx
    ansible.builtin.service:
     state: started 
     name: nginx
    

    