- name: Install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: Install nginx
    name: nginx
    state: present
    ansible.builtin.package:
  - name: start the nginx
    name: nginx
    state: started 
    ansible.builtin.service:


    

    