- name: Play1 and task1 
  hosts: local 
  connection: local 
  tasks:
  - name: play1
    ansible.builtin.debug:
      msg: "hello from play1"
- name: play2 and task2
  hosts: local
  connection: local
  tasks:
  - name: play2
    ansible.builtin.debug:
      msg:  "hello from play2"