- name: variables
  hosts: local
  connection:  local 
  vars:
    course: Devops
    Duration: 120HRS
    Trainer:  Sivakumar
  tasks:
  - name: Play1 and task1
    vars:
      course: Ansible  
    ansible.builtin.debug:
     msg: "course is {{course}}, Duration is {{Duration}}, Trainer is {{Trainer}}"
- name: play2 and task1
  ansible.builtin.debug:
    msg:  "course is :{{course}}, Duration is :{{Duration}}, Trainer is:{{Trainer}}"

 
    


