- name: Variables from files
  hosts: local
  connection: local
  var_files:
  - course.yaml
  tasks:
  ansible.builtin.debug:
    msg:  "course is {{course}}, Duration is {{Duration}},trainer is {{Trainer}}"


