- name: Prompt variables
  hosts:  local
  connection: local
  vars_prompt:
  - name: Course
    msg: "please enter course name"
  - name: Duration
    msg: "please enter Duration"
  - name: Trainer
    msg: "please enter trainer name" 
  tasks:
  - name: Print the course information
    ansible.builtin.debug:
      msg:  "course is {{Course}}, duration is {{Duration}}, trainer is {{Trainer}}" 