- name: Varaibles from Inventory
  hosts:  local
  connection: local
  tasks:
  - name: Print the information
    ansible.builtin.debug:
      msg: "course {{course}},Duration{{Duration}},Trainer{{Trainer}}"