- name: variables from args 
  hosts: local
  connection: local
  tasks:
  - name: print the variable information
    ansible.builtin.debug:
    msg: "course {{ course}}, Duration {{ Duration}}, Trainer {{Trainer}}"