- name: Variable prefernce
  hosts:  local
  connection:  local
  vars:
    GREET: "Play"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: Prompt
    prompt: enter value
    private: false 
  tasks:
  - name: enter task info
    vars: 
     GREET: Task
    ansible.builtin.debug:
     msg: " Hello from {{ GREET}}" 
  