- name: Var preference in files
  hosts:  local
  connection: local 
  vars:
    GREET: "PLAY"
  # vars_files:
  # - course.yaml
  vars_prompt:
  - name: enter play1
    prompt: enter value
    private: false
    msg: "Hello from {{ GREET}}"
  # tasks:
  # - name: print value
  #   # vars: 
  #   #   GREET: "TASK"
  #   ansible.builtin.debug:
  #     msg: "Hello from {{ GREET}}"