- name: loop the information 
  hosts: local 
  connection: local 
  tasks:
    - name: print the information 
      ansible.builtin.debug:
        msg: "Hello {{ item }}"
      loop:
      - Ram 
      - Ganesha
      - Venkat
      - Siva
      - Hanuma 