- name: Install packages
  hosts: web 
  become: yes
  tasks:
  - name: Install packages information
    ansible.builtin.package: 
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'gcc', state: 'present'}
    - {name: 'git', state: 'present'}
    - {name: 'mysql', state: 'absent'}
    - {name: 'zip', state: 'absent'}

