- name: nginx installation
  hosts: all
  # hosts: web
  become: yes
  serial: 4
  tasks:
  - name: nginx install
    ansible.builtin.package: 
      name: nginx
      state: present 
  - name: run nginx
    tags:
     - run
    ansible.builtin.service:
      name: nginx 
      state: started 
